apiVersion: v1
kind: Pod
metadata:
    name: 3024-maintq-pod
    namespace: class-1
    labels:
        app.kubernetes.io/name: 3024-maintq-pod
spec:
    serviceAccountName: default
    containers:
        - name: maintq-fe
          image: amdp-registry.skala-ai.com/skala26a-ai1/a3024:latest
          imagePullPolicy: Always
          resources:
              requests:
                  cpu: '100m'
                  memory: '128Mi'
              limits:
                  cpu: '500m'
                  memory: '256Mi'
          env:
              - name: LOGGING_LEVEL
                value: DEBUG
              - name: USER_NAME
                value: skala
