apiVersion: v1
kind: Service
metadata:
    name: sk3024-maintq-fe
    # Deployment, Ingress와 동일한 네임스페이스
    namespace: skala3-ai1
spec:
    selector:
        # 이 라벨을 가진 Pod으로 트래픽 전달 (Deployment의 labels와 일치)
        app: sk3024-maintq-fe
    ports:
        - port: 8001        # Service가 노출하는 포트 (Ingress에서 참조)
          targetPort: 8001  # 실제 컨테이너 포트
    # 클러스터 내부에서만 접근 가능 (Ingress를 통해 외부 노출)
    type: ClusterIP