# v1 Service - v1 Pod에만 트래픽 전달
apiVersion: v1
kind: Service
metadata:
    name: sk3024-maintq-fe-v1
    namespace: skala3-ai1
spec:
    selector:
        app: sk3024-maintq-fe
        version: v1 # version: v1 라벨이 있는 Pod만 선택
    ports:
        - port: 8001
          targetPort: 8001
    type: ClusterIP
---
# v2 Service - v2 Pod에만 트래픽 전달 (카나리)
apiVersion: v1
kind: Service
metadata:
    name: sk3024-maintq-fe-v2
    namespace: skala3-ai1
spec:
    selector:
        app: sk3024-maintq-fe
        version: v2 # version: v2 라벨이 있는 Pod만 선택
    ports:
        - port: 8001
          targetPort: 8001
    type: ClusterIP
